### ISSUE TITLE
Should we wait for user input to exit?

### ISSUE THREAD

**Issue by nguyenlamlll** [Rhetos/RhetosCli#6]
At these lines

https://github.com/Rhetos/RhetosCli/blob/ea5f5c2c86d7e1e5177f4f2993d7f6e5205ac81c/RhetosCLI/Program.cs#L47-L54

I don't think we should wait for user inputs to actually exit the console. Then, we don't need to check if the command is run in CI environments or run by users.

My assumption is that: When a user run one command, say `rhetos release list`,  the CLI prints all necessary outputs then returns. If user needs something else, he or she keeps on invoking the commands.

**Comment by VladimirZD** [comment]
I am using ReadKey() just to simplify my debugging workflow (in some cases..) it will be removed.
Thnx for suggestion
